on:
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          repository: jesse-ai/jesse
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          push: true
          tags: ghcr.io/TrianaLab/jesse-arm64:${{ inputs.version }}